/**  We cant rely on the MultipartFile info now, so we shall send
 *  it on the Frontend
 */
export type ChunkedMeta = {
  /**
   * A unique ID for the entire file upload. Technically unprotected, but
   * a strong random byte generated by the frontend makes it technically secure.
   */
  uploadId: string
  /** The current chunk's index (0-based) */
  chunkIndex: number
  /** Total number of chunks for the file */
  totalChunks: number
  /** Original name of the file*/
  fileName: string
  /** Total size of the file in bytes*/
  fileSize: number
  /** MIME type of the file*/
  mimeType: string

  /** sha256 of the file */
  chunkHash: string

  /** sha256 of the entire file */
  fileHash: string

  /**
   * The expected size of the chunk
   */
  chunkSize: number
}


